horstoeko\ubl\entities\xades\OCSPValuesType:
    properties:
        encapsulatedOCSPValue:
            expose: true
            access_type: public_method
            serialized_name: EncapsulatedOCSPValue
            xml_element:
                cdata: false
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getEncapsulatedOCSPValue
                setter: setEncapsulatedOCSPValue
            xml_list:
                inline: true
                entry_name: EncapsulatedOCSPValue
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            type: array<horstoeko\ubl\entities\xades\EncapsulatedPKIDataType>
