horstoeko\ubl\entities\cac\EnvironmentalLegislationDocumentReference:
    xml_root_name: EnvironmentalLegislationDocumentReference
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
